### ISSUE TITLE
Feature: User can view a list

### ISSUE THREAD

**Issue by ayshahussain141** [ayshahussain141/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can view a list of books

## 📐 Plan

> ##### A description of how the application will work from the perspective of the user.

Display a list of books on the page

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/46547520/201726031-e42f7200-3a71-4ac3-853b-2c02a434d485.png)
![image](https://user-images.githubusercontent.com/46547520/201729678-dd9db386-18b9-460a-a10a-1fc4721d840b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

  - [x] Add a`div[data-view="books-list"]` element in the HTML.
  - [x] Add an empty unordered list to the `div[data-view="books-list"]` element in the HTML.
  - [x]  Add some dummy journal entries to the unordered list in the HTML and style them to match the wireframe.
  - [x] Define a function that takes a single journal `book` object and returns a DOM tree that matches one of the example entries in the HTML.
- [x] Use a loop to create a DOM tree that creates a list of books in the data model and display it to the page when the `'DOMContentLoaded'` event is fired.
- [x] Remove the example HTML entries once the user's entries are successfully being appended to the DOM on page load.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
