### ISSUE TITLE
Feature: User can Add Book to a Reading List

### ISSUE THREAD

**Issue by ayshahussain141** [ayshahussain141/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can Add book to a reading list

## ⚙️ Wireframes
![image](https://user-images.githubusercontent.com/46547520/202250144-7cee0db2-fbbc-4316-b3d4-fe4ae97b61f9.png)
![image](https://user-images.githubusercontent.com/46547520/202250224-a40e3bba-8697-4d13-849d-9e410892f8bb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

  - [x] Add a button to every list item on the page with a class of [button-add]
  - [x] listen for clicks on the button
  - [x] change the buttons form when books are added
  - [x] store the added list into local storage
       - [x] put the list data into a new object
       - [x] give each list item an id
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
