### ISSUE TITLE
Feature: User can view books in Reading List

### ISSUE THREAD

**Issue by ayshahussain141** [ayshahussain141/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can View Books in reading list

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [x]  Add a sibling `div[data-view="reading-list"]` to the HTML.
- [x]  Add an empty unordered list to the `div[data-view="reading-llist"]` element in the HTML.
- [x] Add some dummy journal entries to the unordered list in the HTML and style them to match the wireframe.
- [x]  Remove the example HTML entries once the user's entries are successfully being appended to the DOM on page load.
- [x] Add a navigation item to the navbar for Reading List.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
