### ISSUE TITLE
Feature: User can Remove book from a reading list

### ISSUE THREAD

**Issue by ayshahussain141** [ayshahussain141/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can Remove book from a reading list
##Wireframes
![image](https://user-images.githubusercontent.com/46547520/202823044-8f062f55-946d-4308-80e5-9f8ec273568c.png)
![image](https://user-images.githubusercontent.com/46547520/202823053-7a49cfa5-387b-44b5-8c04-1f757816d3b2.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create a remove button in the dom tree
- [x]  Remove the entry from the data model and the entry's DOM tree from the page if the user clicks Remove.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
