### ISSUE TITLE
Feature: User can search for a book

### ISSUE THREAD

**Issue by ayshahussain141** [ayshahussain141/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can serach the book in a list to add to reading list

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add a search bar with the` input` on the header container
- [ ] user can search for books
- [ ]add an event listener to the` input` 
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
